version: "3"
services:
    db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
        SA_PASSWORD: "SomeLongPasswordForRequ1rements!"
        ACCEPT_EULA: "Y"
      ports:
      - "9123:1433"
